insert or replace into LocalizedText
    (Language,      Tag,                                                                Text)
values
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_TITLE",                                 "部落联合"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_DESCRIPTION",                           ""),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_EFFECT",                                "你在击败了当地部落后，让剩余的部众对你俯首称臣。你将如何决定这些蛮夷的命运？是接受他们作为边地戍卫，还是将他们抓作劳力，又或是将他们迁徙到附近的城市以作开化？"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_A",                              "戍守边疆"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_B",                              "填充劳力"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_C",                              "徙居城市"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_UNITS",                             "周围三格范围内的{1_Amount}个野蛮人战斗单位消失，在此处为你生成勇士和投石兵各一个"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_BUILDER",                           "周围三格范围内的{1_Amount}个野蛮人战斗单位消失，你在{2_CITYNAME}获得{3_Amount}个建造者"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_POP",                               "周围三格范围内的{1_Amount}个野蛮人战斗单位消失，{2_CITYNAME}获得{3_Amount} [ICON_Citizen] 人口。"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_NO_STATE_LABOR",                        "[COLOR_RED]需要先完成市政“技艺”才能进行选择[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_EVENT_BARB_TRIBE_UNITE_NO_EARLY_EMPIRE",                       "[COLOR_RED]需要先完成市政“对外贸易”才能进行选择[ENDCOLOR]"),   

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_TITLE",                        "精锐勇士"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_DESCRIPTION",                  ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_EFFECT",                       "在征服了两个周边部落后，我们挑选出了各部族的精锐勇士作为常备部队。我们的军事组织空前强大，而他们将作为我们开拓的利刃！"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_CONTINUE",                     "为了部落！"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_UNLOCK",                       "为部落联盟政体增加一个军事政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_TITLE",                        "部落商贸"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_DESCRIPTION",                  ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_EFFECT",                       "在融合了五个周边村庄后，我们初步建立了部落中不同部族间的商贸体系，紧密的商业联系将成为部落团结的关键。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_CONTINUE",                     "为了部落！"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_UNLOCK",                       "为部落联盟政体增加一个经济政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_TITLE",                          "联盟军"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_DESCRIPTION",                    ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_EFFECT",                         "在附庸的城邦进行两次征兵后，我们初步整合了各城邦的军事力量。由各城邦军队组成的联盟军将成为共主联盟最坚实的盾牌。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_CONTINUE",                       "军事霸权的第一步"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_UNLOCK",                         "为城邦共主政体增加一个军事政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_TITLE",                          "朝觐"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_DESCRIPTION",                    ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_EFFECT",                         "完成两次城邦的请求后，我们更进一步的掌控了各城邦的政治与经济。现在，下属的城邦会定期派遣使者到 {1_cityname} 汇报执政情况。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_CONTINUE",                       "经济霸权的第一步"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_UNLOCK",                         "为城邦共主政体增加一个经济政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST1_TITLE",                     "先知启示"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST1_DESCRIPTION",               ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST1_EFFECT",                    "预言中的先知终于到来，他为我们带来了{1_Religion}的教义，并为我们许诺美好的未来。祭司议会已经改组为{1_Religion}的教廷，我们将会把{1_Religion}的教义传播到世界的每一个角落。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST1_CONTINUE",                  "{1_Religion}是唯一正途"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST1_UNLOCK1",                   "为祭司会议政体增加一个军事政策槽位"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST1_UNLOCK2",                   "为祭司会议政体增加一个经济政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST2_TITLE",                     "万神殿"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST2_DESCRIPTION",               ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST2_EFFECT",                    "传说中，我们文明的守护神统治着其他诸神，是最高的主宰。而现在，我们建立了万神殿，来容纳来自不同文明的神灵，我们的祭司能直接得到神灵的启示。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST2_CONTINUE",                  "诸神殿堂降临人间"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST2_UNLOCK1",                   "为祭司会议政体增加一个军事政策槽位"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_QUEST2_UNLOCK2",                   "为祭司会议政体增加一个经济政策槽位"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_TITLE",                          "洪水之后"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_DESCRIPTION",                    ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_EFFECT",                         "洪水淹没了{1_cityname}的周边地区，多亏了大浴场配套的水利设施，我们第{2_times}次几乎没有损失的度过了灾难。祭司将{1_cityname}的市民们召集在大浴场，在进行祭祀后宣布了洪水的善后措施。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_CHOICE_A",                       "庆祝劫后余生"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_CHOICE_B",                       "收容洪水难民"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_CHOICE_C",                        "扩建城市规模"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_GET_AMENITY",                    "为{1_cityname}+1 [ICON_Amenities] 宜居度"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_GET_POP",                        "为{1_cityname}+1 [ICON_Citizen] 人口"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_GET_HOUSING",                    "为{1_cityname}+2 [ICON_Housing] 住房"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_GREAT_BATH_FLOOD_NO_HOME",                        "[COLOR_RED]{1_cityname} 没有足够的住房，不能收容更多难民[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_CHOICE_TITLE",                     "信仰分歧"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_CHOICE_DESCRIPTION",               ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_CHOICE_EFFECT",                    "随着我们逐渐接触到其他文明的不同信仰，祭司议会的长老们在对待信仰方式的上出现了分歧。一些长老认为保持对现有信仰的专一虔信才是正途，另一些则坚持不同文明的众神都有各自的权能。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_CHOICE_CHOICE_A",                  "遵奉唯一信仰"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_CHOICE_CHOICE_B",                  "诸神各有权柄"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_CHOICE_MONOTHEISM",                "[ICON_FAITH] 信仰值将被转化为 [ICON_GREATPROPHET] 大预言家点数，直到你招募了一名大预言家（或者所有大预言家已经被招募）"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_CHOICE_POLYTHEISM",                "允许用{1_Amount} [ICON_FAITH] 信仰值购买已宣布友好的文明的万神殿"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PRIEST_COUNCIL_CHOICE_BAN_MONOTHEISM",            "[COLOR_RED]你的文明或领袖无法获得大预言家[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PURCHASE_PANTHEON_TITLE",                         "引入外来信仰"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PURCHASE_PANTHEON_DESCRIPTION",                   ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PURCHASE_PANTHEON_EFFECT",                        "在与{1_CivName}交流日益增多后，他们信奉的“{2_Pantheon}”也随之传入我国。是否需要在我们的万神殿里设立{2_Pantheon}的神位？"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PURCHASE_PANTHEON_CHOICE_A",                      "引入外来神灵"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PURCHASE_PANTHEON_CHOICE_B",                      "本地神仙就够用了"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PURCHASE_PANTHEON_PURCHASE",                      "获得{1_Pantheon}的能力，其效果是{2_PantheonEffect}"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PURCHASE_PANTHEON_COST",                          "消耗{1_Amount} [ICON_FAITH] 信仰值"),
    --("zh_Hans_CN",  "LOC_EVENT_COMMON_PURCHASE_PANTHEON_PARDON",                        ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_PURCHASE_PANTHEON_NO_FAITH",                      "[COLOR_RED][ICON_FAITH] 信仰值不足{1_Amount}[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_TITLE",                                      "壁画艺术"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_DESCRIPTION",                                ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_EFFECT",                                     "这个村庄的村民会制作很多颜料绘制壁画，连{1_CITYNAME}的艺术家看到了都会感叹壁画之鲜艳多彩。也许我们可以带走最好的壁画，又或者，让我们的艺术家来研究一下？"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_CHOICE_A",                                   "搬走最好的壁画"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_CHOICE_B",                                   "学习壁画的颜料"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_CULTURE",                                    "宫殿+1 [ICON_Culture] 文化值[NEWLINE]完成帝国初期后改为+2 [ICON_Culture] 文化值"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MURAL_SCIENCE",                                    "宫殿+1 [ICON_Science] 科技值[NEWLINE]完成砌砖后改为+2 [ICON_Science] 科技值"),


    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_TITLE",                            "人祭"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_DESCRIPTION",                      ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_EFFECT",                           "这里的聚落似乎正在用动物和活人进行祭祀以取悦鬼神，他们一开始尝试抓住你的使者，但很快就被击退。在成功进行交流后，他们邀请你也来参加祭祀。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_CHOICE_A",                         "用动物祭祀"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_CHOICE_B",                         "用活人祭祀"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_GAIN_FAITH",                       "获得{1_AMOUNT} [ICON_FAITH] 信仰值"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_LOSE_POP",                         "{1_CITYNAME}失去 1 [ICON_CITIZEN] 人口"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_NO_POP_TO_LOSE",                   "[COLOR_RED]{1_CITYNAME}人口不足2，无法失去 [ICON_CITIZEN] 人口[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_TITLE",                               "制图专家"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_DESCRIPTION",                         ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_EFFECT",                              "这里的村民很快就猜到了我们的{1_UNITNAME}来自哪里，原来当地有一户人家擅长制作地图，为村落外出交流提供了很大的便利。也许我们应该拿走他们的地图，或者请他们加入我们的队伍？"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_CHOICE_A",                            "抢走地图"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_CHOICE_B",                            "抓走制图师"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_SHOW_MAP",                            "获得6格内的地图"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_CARTOGRAPHER_HORIZON",                             "你的{1_UNITNAME}获得1额外视野"),
    ("zh_Hans_CN",  "LOC_ABILTY_EVENT_GOODY_CARTOGRAPHER_DESCRIPTION",                  "+1额外视野，来自绑架的制图师。"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_TITLE",                                 "神奇的草药"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_DESCRIPTION",                           ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_EFFECT",                                "村民向你献上几种草药，据说在祭祀中服用这些草药就可以与神灵交流。他们提醒你，这些草药只有在生吃时才会有最大的效力。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_CHOICE_A",                              "那就生吃吧"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_CHOICE_B",                              "熟食才安全"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_KILL_UNIT",                             "你的{1_UNITNAME}遇害了"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_FAITH",                                 "获得{1_AMOUNT} [ICON_FAITH] 信仰值"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_HEAL_UNIT",                             "你的{1_UNITNAME}恢复了全部生命值"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_MAGIC_HERB_MOVEMENT",                              "你的{1_UNITNAME}立刻获得5点 [ICON_MOVEMENT] 移动力"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_TITLE",                                     "饥荒"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_DESCRIPTION",                               ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_EFFECT",                                    "也许我们来晚了，但也许还没有那么晚。这一带的饥荒已经持续了一段时间了，我们的{1_UNITNAME}来到这里就是这里最大的救星。我们可以带走那些还有余力跟着我们{1_UNITNAME}的民众，但带走更多的人，就需要{2_CITYNAME}的帮助了。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_CHOICE_A",                                  "带走还能行动的人"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_CHOICE_B",                                  "从{1_CITYNAME}派出救援队伍"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_GAIN_1_POPULATION",                         "{1_CITYNAME}获得1 [ICON_Citizen] 公民"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_GAIN_2_POPULATION",                         "{1_CITYNAME}获得2 [ICON_Citizen] 公民"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_PAY_GOLD",                                  "失去100 [ICON_Gold] 金币"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FAMINE_NO_GOLD_TO_LOSE",                           "[COLOR_RED] [ICON_Gold] 金币不足100，无法进行援助。[ENDCOLOR]"),


    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_TITLE",                      "古老工事"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_DESCRIPTION",                ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_EFFECT",                     "我们的{1_UNITNAME}到达村庄时，村子里的人早已躲进了一座看起来颇有年头的防御工事里。工事看起来颇为完备，易守难攻，但破败的墙体也说明这里并非没有破绽可寻。是组织强攻，还是搜刮村里留下的物资就走？。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_CHOICE_A",                   "组织进攻"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_CHOICE_B",                   "搜刮物资"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_GOOD_END",                   "25%概率触发事件“攻克工事”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_BAD_END",                    "75%概率你的{1_UNITNAME}失去25生命值，触发事件“没有进展”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_STOP",                       "获得25 [ICON_GOLD] 金币"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_NO_STRENNGTH",               "[COLOR_RED]只有战斗单位才能进行此项[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_TITLE",                    "攻克工事"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_DESCRIPTION",              ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_EFFECT",                   "长久的进攻后，工事终于被拿下，我们的{1_UNITNAME}胜利凯旋"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_CONTINUE",                 "伟大胜利！"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_GOLD",                     "获得100 [ICON_GOLD] 金币"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_PROMOTION",                "你的{1_UNITNAME}获得一次升级"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_TITLE",                    "没有进展"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_DESCRIPTION",              ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_EFFECT",                   "数次针对工事薄弱点的进攻均无功而返，我们的{1_UNITNAME}也损失惨重。还要继续吗？"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_CHOICE_A",                 "继续！"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_CHOICE_B",                 "见好就收"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_GOOD_END",                 "25%概率触发事件“攻克工事”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_BAD_END",                  "75%概率你的{1_UNITNAME}失去25生命值，触发事件“没有进展”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_STOP",                     "获得25 [ICON_GOLD] 金币"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_UNIT_KILLED",              "[COLOR_RED]在上一轮进攻中，你的{1_UNITNAME}已溃败[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_NO_HOME_TITLE",                                    "居无定所"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_NO_HOME_DESCRIPTION",                              ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_NO_HOME_EFFECT",                                   "这里的人们被其他文明排斥，居无定所。你可以让他们留在你的帝国吗？或者让周边的小国接纳他们？"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_NO_HOME_CHOICE_A",                                 "派驻官员"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_NO_HOME_CHOICE_B",                                 "迁徙他国"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_NO_HOME_GAIN_SETTLER",                             "在此获得一个开拓者"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_NO_HOME_LOSE_GOVERNOR",                            "失去一个 [ICON_GOVERNOR] 总督头衔"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_NO_HOME_GAIN_ENVOY",                               "获得一个 [ICON_Envoy] 使者"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_NO_HOME_NO_GOVERNOR_TO_LOSE",                      "[COLOR_RED]需要至少拥有一个 [ICON_GOVERNOR] 总督头衔以派遣官员[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_LAND_STAR_TITLE",                                  "地上的星星"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_LAND_STAR_DESCRIPTION",                            ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_LAND_STAR_EFFECT",                                 "这里的人们在崇拜一个造型独特的巨石，据他们声称，这是天上的星星掉了下来，是神灵的使者。而你的顾问却告诉你这只是一块上好的铁矿石，熔了作为武器才是最佳选择。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_LAND_STAR_CHOICE_A",                               "熔化“星星”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_LAND_STAR_CHOICE_B",                               "用铁器交换“星星”"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_LAND_STAR_GAIN_IRON",                              "获得20 [ICON_RESOURCE_IRON] 铁"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_LAND_STAR_LOSE_IRON",                              "失去20 [ICON_RESOURCE_IRON] 铁"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_LAND_STAR_GAIN_RELICS",                            "获得一份随机 [ICON_GREATWORK_RELIC] 遗物"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_LAND_STAR_NO_IRON_TO_LOSE",                        "[COLOR_RED] [ICON_RESOURCE_IRON] 铁不足20，无法进行交换。[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FOREIGN_CARANAVS_TITLE",                           "异域商队"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FOREIGN_CARANAVS_DESCRIPTION",                     ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FOREIGN_CARANAVS_EFFECT",                          "你遇到了一个自称来自远方的商队，他们的货物在途中漂没，现在没有足够的资源回到家乡。他们恳求你接纳商队在这里暂时生活，并向你讲述远方国度的各种奇珍异宝。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FOREIGN_CARANAVS_CHOICE_A",                        "让他们在这定居"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FOREIGN_CARANAVS_CHOICE_B",                        "投资商队，开拓商路"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FOREIGN_CARANAVS_CHOICE_A_EFFECTS_GET_HORSES",     "获得20 [ICON_RESOURCE_HORSES] 马"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FOREIGN_CARANAVS_CHOICE_B_DISABLED",               "[COLOR_RED]需要有20 [ICON_RESOURCE_HORSES] 马以进行投资[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FOREIGN_CARANAVS_CHOICE_B_EFFECTS_GET_TRADE",      "获得1 [ICON_TradeRouteLarge] 商路容量"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_FOREIGN_CARANAVS_CHOICE_B_EFFECTS_LOSE_HORSES",    "失去20 [ICON_RESOURCE_HORSES] 马"),
 
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_VAGRANT_ACROBATIC_TITLE",                          "流浪杂技团"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_VAGRANT_ACROBATIC_DESCRIPTION",                    ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_VAGRANT_ACROBATIC_EFFECT",                         "你遇到了一群进行奇怪表演的艺人，他们在空中做出各种危险动作，又有惊无险地安全着陆。你的顾问认为这些人不事生产，做奇怪行为博人眼球，应该教育他们进行劳作，可你却觉得有时候看看这种表演也挺有意思的。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_VAGRANT_ACROBATIC_CHOICE_A",                       "请他们来{1_CITY}表演"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_VAGRANT_ACROBATIC_CHOICE_B",                       "在{1_CITY}禁止杂技表演"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_VAGRANT_ACROBATIC_GET_CITY_AMENITIES",             "{1_CITY}+2 [ICON_Amenities] 宜居度"),
    --("zh_Hans_CN",  "LOC_EVENT_GOODY_VAGRANT_ACROBATIC_GET_GOLD",                       "获得80 [ICON_GOLD] 金币"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_VAGRANT_ACROBATIC_LOSE_CITY_AMENITIES",            "{1_CITY}-2 [ICON_Amenities] 宜居度"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_TITLE",                                     "民间智慧"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_DESCRIPTION",                               ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_EFFECT",                                    "你的公民来到了一个朴素却整洁的聚居地，在这里不时能看到用各种方式演算的思索者，长老们热情的接待了你的使者，想传授一些特别的智慧——[Newline]"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_CONTINUE",                                  "接纳这份智慧"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_EFFECT_1",                                  "未曾发现的领域！你的文明获得了关于{1_techname}的启发。"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_EFFECT_2",                                  "最后的环节终于畅通了！你的文明一鼓作气完成了{1_techname}的研究"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_EFFECT_3",                                  "他们告诉了你关于{1_techname}的知识，然而这在你的帝国只不过是常识！这让他们的学者大为赞叹，慕名来访。"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_1",                                         "获得{1_techname}的尤里卡"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_2",                                         "完成{1_techname}科技"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_EUREKA_3",                                         "获得{1_techname}花费一半的科技值（+{2_Amount} [ICON_SCIENCE] 科技值）。"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_TITLE",                                "模范社区"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_DESCRIPTION",                          ""),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_EFFECT",                               "你的公民来到了一个井井有条的聚居地，这里的社会组织令人感到耳目一新。在经过一番调查后——[Newline]"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_CONTINUE",                             "寻找组织之道"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_EFFECT_1",                             "全新的组织形式！你的文明获得了{1_Civname}的启发"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_EFFECT_2",                             "观摩了{1_Civname}的实际运作后！你的文明也将{1_Civname}从纸面带到了实践"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_EFFECT_3",                             "{1_Civname}？这在我们的帝国早已司空见惯，但能在这样的小地方发生作用倒也是令人惊奇。"),

    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_1",                                    "获得{1_Civname}的鼓舞"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_2",                                    "完成{1_Civname}市政"),
    ("zh_Hans_CN",  "LOC_EVENT_GOODY_INSPIRATION_3",                                    "获得{1_Civname}花费一半的文化值（+{2_Amount} [ICON_CULTURE] 文化值）。"),


    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_WAKE_TITLE",                               "跨过卢比孔河"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_WAKE_DESCRIPTION",                         ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_WAKE_EFFECT",                              "剑盾轰鸣，军势咆吼。共和国敌早已掷下他的血骰，十三军团不为卢比孔河回首。[Newline]纵尔亡命天涯与海角，不啻我来我见我征服。拜倒于脚下的元老院，亦不过被时代抛弃的髑髅。[newline]神祖在上，魂佑罗马；艳后在旁，智定天下——你的誓言，以传唱千古的“凯撒”之名，久久回荡于七丘。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_WAKE_CONTINUE",                            "属于我们的时代，开始了"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_WAKE_UNLOCK",                              "解锁觉醒技，“凯撒”"),
    
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_CHANGE_GOVENRMENT_TITLE",                  "儒略万法的源头"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_CHANGE_GOVENRMENT_DESCRIPTION",            ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_CHANGE_GOVENRMENT_NOTHING_EFFECT",         "混乱的无政府状态"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_CHANGE_GOVENRMENT_EFFECT",                 "老方法自有好处，但......贵人派的确在质询他们的领袖。“你递来了一封信，只是写上了‘我来 我见 我征服’，那你真来了吗，到底来没来——”当然，你来了，并带来了那个崭新的，不可用冗长的辩论语言描述的真理。“闭嘴！”刚刚做出了{1_PrveGovernmentId}转为{2_ThisGovernmentId}）决定的你，对他们如是说。以及，为了保留对旧秩序的些微尊重，是时候阅读他们的陈情书了。"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_CHANGE_GOVENRMENT_CONTINUE",               "转变政体"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_CAESAR_CHANGE_GOVENRMENT_UNLOCK",                 "转变政体"),

    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_ANCIENT_TITLE",                         "进入远古时代"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_ANCIENT_DESCRIPTION",                   ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_ANCIENT_EFFECT",                        "从水下第一个生命的萌芽开始…到石器时代的巨型野兽…再到人类第一次直立行走，你已经历许多。现在，开启你最伟大的探索吧：从早期文明的摇篮到浩瀚星宇。[NEWLINE]时代增益[newline][ICON_Barbarian]部落融合：清理蛮族哨站后，除了平常的经验值和金币，你还能将周围三格内的蛮族单位转化为我方单位，完成“帝国初期”和“国家劳动力”市政后，你还可以选择将其转化为 [ICON_CITIZEN] 城市人口或 [ICON_Charges] 建造者。与野蛮人作战获取经验没有等级上限。[NEWLINE]"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_ANCIENT_CONTINUE",                      "开始探索"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_ANCIENT_UNLOCK",                        ""),


    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_CLASSICAL_TITLE",                       "进入古典时代"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_CLASSICAL_DESCRIPTION",                 ""),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_CLASSICAL_EFFECT",                      "从卑微的最初，你就展示出了非凡的成长力。从青铜到钢铁，用马匹和刀剑来统治吧。天空开始揭示出自己的秘密，宇宙让我们为之兴奋，星空指引我们来到异国海岸。[NEWLINE]时代增益[newline][ICON_GreatPerson]百家争鸣：来自 [icon_enlightment] 启明的 [ICON_GreatPerson] 伟人点数翻倍。[NEWLINE]"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_CLASSICAL_CONTINUE",                    "群星闪耀"),
    ("zh_Hans_CN",  "LOC_EVENT_COMMON_ENTER_ERA_CLASSICAL_UNLOCK",                      "");



insert or replace into LocalizedText
    (Language,      Tag,                                                                Text)
values
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_TITLE",                                 "Tribal Confederation"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_DESCRIPTION",                           ""),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_EFFECT",                                "As the leader of tribal confederate, you have defeated the local tribes and forced the others to bend their knees. How will you decide the fate of these barbarians? Will you accept them as border guards, capture them as forced labor, or relocate them to nearby cities and make them civilized?"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_A",                              "Border Guard"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_B",                              "Forced Labor"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_CHOICE_C",                              "Relocation"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_UNITS",                             "{1_Amount} nearby Barbarian combat units are converted to yours."),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_BUILDER",                           "{1_Amount} nearby Barbarian combat units disappear, and you receive {2_Amount} Builders."),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_GET_POP",                               "{1_Amount} nearby Barbarian combat units disappear, {2_CITYNAME} receives {1_Amount} [ICON_Citizen] Population."),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_NO_STATE_LABOR",                        "[COLOR_RED]Can only be chosen after researching the State Workforce civic.[ENDCOLOR]"),
    ("en_US",  "LOC_EVENT_BARB_TRIBE_UNITE_NO_EARLY_EMPIRE",                       "[COLOR_RED]Can only be chosen after researching the Early Empire civic.[ENDCOLOR]"),   

    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_TITLE",                        "Military Reforms"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_DESCRIPTION",                  ""),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_EFFECT",                       "After conquering two nearby tribes, we have chosen veteran warriors from every tribe to form a standing army. Our military organization is stronger than ever, and they will serve as the blade to cut open the way of expansion!"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_CONTINUE",                     "For the horde!"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST1_UNLOCK",                       "Adds a military policy slot for the Tribal Confederate government."),

    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_TITLE",                        "Economic Reforms"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_DESCRIPTION",                  ""),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_EFFECT",                       "After assimilating five nearby villages, we have established the commerce system among different clans in our horde, a tight trade relationship among clans will be key to our unity."),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_CONTINUE",                     "For the horde!"),
    ("en_US",  "LOC_EVENT_COMMON_TRIBE_UNITY_QUEST2_UNLOCK",                       "Adds an economic policy slot for the Tribal Confederate government."),

    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_TITLE",                          "Military Reforms"),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_DESCRIPTION",                    ""),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_EFFECT",                         "The military traditions of {1_CITYNAME} have brought us better understanding with establishing an army, now we can face war with ease."),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_CONTINUE",                       "The first step to military hegemony"),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST1_UNLOCK",                         "Adds a military policy slot for the City-State Suzerainty government."),

    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_TITLE",                          "Economic Reforms"),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_DESCRIPTION",                    ""),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_EFFECT",                         "The economic traditions of {1_CITYNAME} have brought us better understanding with commere. Now, the prosperity of our trade network is unprecendented."),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_CONTINUE",                       "The first step to economic hegemony"),
    ("en_US",  "LOC_EVENT_COMMON_CITYSTATE_QUEST2_UNLOCK",                         "Adds an economic policy slot for the City-State Suzerainty government."),

    ("en_US",  "LOC_EVENT_GOODY_MURAL_TITLE",                                      "Cave Painting Arts"),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_DESCRIPTION",                                ""),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_EFFECT",                                     "The residents of this village know how to mix dyes to draw cave paintings, even the artists of {1_CITYNAME} praised the vividness of their colors. Maybe we can take the finest cave paintings, or maybe, leave them to the study of our artists?"),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_CHOICE_A",                                   "Take the finest cave paintings"),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_CHOICE_B",                                   "Study about the dyes"),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_CULTURE",                                    "+1 [ICON_Culture] Culture to the Palace[NEWLINE]Increased to +2 [ICON_Culture] Culture after researching the Early Empire civic."),
    ("en_US",  "LOC_EVENT_GOODY_MURAL_SCIENCE",                                    "+1 [ICON_Science] Science to the Palace[NEWLINE]Increased to +2 [ICON_Science] Science after researching the Masonry technology."),


    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_TITLE",                            "Human Sacrifice"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_DESCRIPTION",                      ""),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_EFFECT",                           "This settlement seems to be sacrificing animals and living humans to please the ghosts and deities. They tried to capture your messengers in the first place, but we fought them back. After a successful discussion, they have invited you to join the ritual."),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_CHOICE_A",                         "Sacrifice with animals"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_CHOICE_B",                         "Sacrifice with humans"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_GAIN_FAITH",                       "Receive {1_AMOUNT} [ICON_FAITH] Faith"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_LOSE_POP",                         "{1_CITYNAME} loses 1 [ICON_CITIZEN] Population"),
    ("en_US",  "LOC_EVENT_GOODY_HUMAN_SACRIFICE_NO_POP_TO_LOSE",                   "[COLOR_RED]{1_CITYNAME} has less than 2 [ICON_CITIZEN] Population, cannot lose [ICON_CITIZEN] Population any more[ENDCOLOR]"),

    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_TITLE",                               "Cartographer"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_DESCRIPTION",                         ""),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_EFFECT",                              "The villagers here figures out when our {1_UNITNAME} came from in the blink of an eye. It turns out that there is a local family who is good at making maps, which provides a great convenience for the village to reach out beyond their border. Maybe we should take their maps, or let them join our team?"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_CHOICE_A",                            "Take the map"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_CHOICE_B",                            "Kidnap the cartographer"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_SHOW_MAP",                            "Reveals map within 6 tiles"),
    ("en_US",  "LOC_EVENT_GOODY_CARTOGRAPHER_HORIZON",                             "Your {1_UNITNAME} receives +1 additional sight"),
    ("en_US",  "LOC_ABILTY_EVENT_GOODY_CARTOGRAPHER_DESCRIPTION",                  "+1 additional sight, from the kidnapped cartographer"),

    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_TITLE",                                 "Mysterious Herbs"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_DESCRIPTION",                           ""),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_EFFECT",                                "The villagers present you with several herbs, legends said they allow communication with the spirits when taken during rituals. They remind you that these herbs are only potent when eaten raw."),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_CHOICE_A",                              "Eat it raw"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_CHOICE_B",                              "Cooked food is safer"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_KILL_UNIT",                             "Your {1_UNITNAME} dies"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_FAITH",                                 "Receive {1_AMOUNT} [ICON_FAITH] Faith"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_HEAL_UNIT",                             "Your {1_UNITNAME} fully heals"),
    ("en_US",  "LOC_EVENT_GOODY_MAGIC_HERB_MOVEMENT",                              "Your {1_UNITNAME} receives 5 [ICON_MOVEMENT] Movement immediately"),

    ("en_US",  "LOC_EVENT_GOODY_FAMINE_TITLE",                                     "Famine"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_DESCRIPTION",                               ""),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_EFFECT",                                    "We may come late, but not too late. Maybe we're late to the party, but maybe not that late. The famine in this area has been going on for some time now, and our {1_UNITNAME} coming here is the greatest savior here. We can bring the people who still have remaining stamina to follow our {1_UNITNAME}, but taking more people will require the help of {2_CITYNAME}."),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_CHOICE_A",                                  "Take those who can still walk"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_CHOICE_B",                                  "Send a rescue team from {1_CITYNAME}"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_GAIN_1_POPULATION",                         "{1_CITYNAME} receives 1 [ICON_Citizen] Population"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_GAIN_2_POPULATION",                         "{1_CITYNAME} receives 2 [ICON_Citizen] Population"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_PAY_GOLD",                                  "Lose 100 [ICON_Gold] Gold"),
    ("en_US",  "LOC_EVENT_GOODY_FAMINE_NO_GOLD_TO_LOSE",                           "[COLOR_RED] Less than 100 [ICON_Gold] Gold, cannot send a rescue team[ENDCOLOR]"),


    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_TITLE",                      "Seasoned Fortification"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_DESCRIPTION",                ""),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_EFFECT",                     "When our {1_UNITNAME} reached the village, the villagers had taken refuge in a fortification that looked quite old. The fortification looked well established and highly defensible, but the crumbling walls showed it is not flawless. Should we launch a siege, or just scavenge the supplies left behind in the village and leave?"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_CHOICE_A",                   "Launch a Siege"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_CHOICE_B",                   "Scavenge the Supplies"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_GOOD_END",                   "30% to trigger the event“Successful Siege”"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_BAD_END",                    "70% to trigger the event “Stalemate”, and your {1_UNITNAME} loses 25 HP"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_STOP",                       "Receives 25 [ICON_GOLD] Gold"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_NO_STRENNGTH",               "[COLOR_RED]Only combat unit can choose this option[ENDCOLOR]"),

    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_TITLE",                    "Successful Siege"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_DESCRIPTION",              ""),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_EFFECT",                   "After a prolonged siege, the fortification is captured, and our {1_UNITNAME} triumphs in victory"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_CONTINUE",                 "A great victory!"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_GOLD",                     "Receives 100 [ICON_GOLD] Gold"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_1_PROMOTION",                "Your {1_UNITNAME} receives a promotion"),

    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_TITLE",                    "Stalemate"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_DESCRIPTION",              ""),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_EFFECT",                   "Several attacks against weak points of the fortifications were unsuccessful, and our {1_UNITNAME} suffered heavy casualties. Should we continue?"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_CHOICE_A",                 "Push on!"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_CHOICE_B",                 "Retreat"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_GOOD_END",                 "30% to trigger the event“Successful Siege”"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_BAD_END",                  "70% to trigger the event “Stalemate”, and your {1_UNITNAME} loses 25 HP”"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_STOP",                     "Receives 25 [ICON_GOLD] Gold"),
    ("en_US",  "LOC_EVENT_GOODY_ANCIENT_FORTIFICATION_2_UNIT_KILLED",              "[COLOR_RED]Your {1_UNITNAME} is routed during the last siege[ENDCOLOR]");




