insert or replace into LocalizedText
    (Language,      Tag,                                                        Text)
values
    ("zh_Hans_CN",  "LOC_GOVERNOR_GOVERNOR_TITLES_AVAILABLE",                           "可用总督头衔 {1_Amount}"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_GOVERNOR_TITLES_SPENT",                               "已用于任命总督的总督头衔 {1_Amount}"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_GOVERNOR_TITLES_HIDE",                                "已用于加强政府的总督头衔 {1_Amount}"),
    ("zh_Hans_CN",  "LOC_BUY_POLICY_SLOT",                                              "强化政府"),

    ("zh_Hans_CN",  "LOC_MILITARY_ADD",                                                 "强化政府[NEWLINE]消耗 1 [ICON_GOVERNOR] 总督头衔增加1个政策槽位。[NEWLINE]目前已有 {1_Amount} [ICON_GOVERNOR] 总督头衔用于兑换军事政策槽位。切换政府类型时会归还所有用于加强政府的总督点数。"),
    ("zh_Hans_CN",  "LOC_ECONOMIC_ADD",                                                 "强化政府[NEWLINE]消耗 1 [ICON_GOVERNOR] 总督头衔增加1个政策槽位。[NEWLINE]目前已有 {1_Amount} [ICON_GOVERNOR] 总督头衔用于兑换经济政策槽位。切换政府类型时会归还所有用于加强政府的总督点数。"),
    ("zh_Hans_CN",  "LOC_DIPLOMATIC_ADD",                                               "强化政府[NEWLINE]消耗 1 [ICON_GOVERNOR] 总督头衔增加1个政策槽位。[NEWLINE]目前已有 {1_Amount} [ICON_GOVERNOR] 总督头衔用于兑换外交政策槽位。切换政府类型时会归还所有用于加强政府的总督点数。"),
    ("zh_Hans_CN",  "LOC_WILDCARD_ADD",                                                 "强化政府[NEWLINE]消耗 1 [ICON_GOVERNOR] 总督头衔增加1个政策槽位。[NEWLINE]目前已有 {1_Amount} [ICON_GOVERNOR] 总督头衔用于兑换文化政策槽位。切换政府类型时会归还所有用于加强政府的总督点数。"),

    ("zh_Hans_CN",  "LOC_MILITARY_INFO",                                                "是否消耗 1 [ICON_GOVERNOR] 总督头衔增加1个政策槽位？切换政府类型后会归还所有用于强化政府的总督点数。"),
    ("zh_Hans_CN",  "LOC_ECONOMIC_INFO",                                                "是否消耗 1 [ICON_GOVERNOR] 总督头衔增加1个政策槽位？切换政府类型后会归还所有用于强化政府的总督点数。"),
    ("zh_Hans_CN",  "LOC_DIPLOMATIC_INFO",                                              "是否消耗 1 [ICON_GOVERNOR] 总督头衔增加1个政策槽位？切换政府类型后会归还所有用于强化政府的总督点数。"),
    ("zh_Hans_CN",  "LOC_WILDCARD_INFO",                                                "是否消耗 1 [ICON_GOVERNOR] 总督头衔增加1个政策槽位？切换政府类型后会归还所有用于强化政府的总督点数。"),
 
    ("zh_Hans_CN",  "LOC_TOP_PANEL_GOVERNOR",                                           "总督头衔"),
    ("zh_Hans_CN",  "LOC_TOP_PANEL_UNITY_TOOLTIP_GOVERNORS",                            "{1_Amount} [ICON_GOVERNOR] 总督头衔可用"),
    ("zh_Hans_CN",  "LOC_TOP_PANEL_UNITY_TOOLTIP_THRESHOLD",                            "在凝聚力达到 {1_Amount} 时，可获得1 [ICON_GOVERNOR] 总督头衔"),
    ("zh_Hans_CN",  "LOC_TOP_PANEL_UNITY_TOOLTIP_BALANCE",                              "{1_Amount} 凝聚力点数"),
    ("zh_Hans_CN",  "LOC_UNITY_SOURCE_QIN_WATER_DISTRICT_DESCRIPTION",                  "每 [ICON_Turn] 回合+ {1_Amount} 凝聚力点数，来自水利区域"),
    ("zh_Hans_CN",  "LOC_UNITY_SOURCE_GOVERNMENT_BUILDING_DESCRIPTION",                 "每 [ICON_Turn] 回合+ {1_Amount} 凝聚力点数，来自市政广场建筑"),
    ("zh_Hans_CN",  "LOC_UNITY_SOURCE_POLICY_DESCRIPTION",                              "每 [ICON_Turn] 回合+ {1_Amount} 凝聚力点数，来自政策"),
	("zh_Hans_CN",  "LOC_UNITY_SOURCE_ZHISUO_DESCRIPTION",                              "每 [ICON_Turn] 回合+ {1_Amount} 凝聚力点数，来自治所"),
    ("zh_Hans_CN",  "LOC_TOP_PANEL_UNITY_TOOLTIP_RATE_FROM_DOUBLE_POLICY",              "每 [ICON_Turn] 回合- {1_Amount} 凝聚力点数，来自加倍使用的政策卡"),
    ("zh_Hans_CN",  "LOC_TOP_PANEL_UNITY_TOOLTIP_SOURCES_HELP",                         "政体建筑和政策是凝聚力点数的主要来源。"),

    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_THE_BISHOP_NAME",                  "教父"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_THE_BISHOP_DESCRIPTION",           "本城训练的使徒、传教士、上师、审判+2 [ICON_MOVEMENT] 移动力，+1使用次数。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_MENTOR_NAME",                      "导师"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_MENTOR_DESCRIPTION",               "本城每位公民+2 [ICON_Faith] 信仰值。获得+4 [ICON_GREATPROPHET] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_HOLY_ORDER_NAME",                  "圣团"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_HOLY_ORDER_DESCRIPTION",           "信仰值购买使徒、传教士的价格-25%，本城对相邻城市释放的宗教压力强度加倍。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_TEMPLE_PRECINCT_NAME",             "神庙辖区"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_TEMPLE_PRECINCT_DESCRIPTION",      "本城训练的传教士可以花费次数，使用 [ICON_Faith] 信仰值完成区域的建造。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_CONSECRATION_NAME",                "祝圣仪式"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_CONSECRATION_DESCRIPTION",         "本城训练的使徒可以花费次数，使所在区域的相邻加成提供等量的信仰值。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_FINAL_NAME",                       "最终能力"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_CARDINAL_FINAL_DESCRIPTION",                "很厉害的最终能力，但还没有做"),  

    ("zh_Hans_CN",  "LOC_UNITCOMMAND_MISSIONARY_BUILD_DISTRICT_NAME",                   "建立神庙辖区"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_MISSIONARY_BUILD_DISTRICT_DESCRIPTION",            "本单位进入正在建造中的区域所在单元格后，可以消耗宗教传播次数，使用 [icon_faith] 信仰值完成区域建造。"),
    ("zh_Hans_CN",  "LOC_UNIT_FAITHBUILDER_NO_DISTRICTS",                               "[COLOR_Red]单位需要位于己方境内正在建造中的区域上[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_UNIT_FAITHBUILDER_NO_FAITH",                                   "[COLOR_Red]需要至少拥有{1_amount} [icon_faith] 信仰值完成建造[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_UNITCOMMAND_APOSTLE_FAITH_NAME",                               "举行祝圣仪式"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_APOSTLE_FAITH_DESCRIPTION",                        "本单位进入已完成的区域所在单元格后，可以消耗宗教传播次数，使其提供 [icon_science] 科技值，[icon_culture] 文化值和 [icon_faith] 信仰值相邻加成等量的 [icon_faith] 信仰值"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_APOSTLE_FAITH_DISABLED",                           "[COLOR_Red]单位需要位于己方境内已完成的区域上[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_APOSTLE_FAITH_USED",                               "[COLOR_Red]该区域已经进行过祝圣[ENDCOLOR]"),


    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_LEADER_NAME",                       "工会首领"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_LEADER_DESCRIPTION",                "此城市中生产的所有建造者将+1 [ICON_Charges] 劳动力+2 [ICON_MOVEMENT] 移动力。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_ZONER_NAME",                        "规划委员"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_ZONER_DESCRIPTION",                 "本城可以无视人口限制额外建造一个专业区域。城市建造区域速度+50%。"),  
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_INFRASTRUCTURE_NAME",               "基础设施"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_INFRASTRUCTURE_DESCRIPTION",        "本城生产的建造者可以花费1 [ICON_Charges] 劳动力为所在单元格+1 [ICON_Production] 生产力或+1 [icon_food] 食物（两种产出不能共存，且不可叠加）。"),  
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_VOLUNTARY_LABOR_NAME",              "义务劳动"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_VOLUNTARY_LABOR_DESCRIPTION",       "城市每有一个专业区域，就为本城每位公民+0.5 [ICON_Production] 生产力。"),  
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_MASTER_NAME",                       "建筑大师"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_MASTER_DESCRIPTION",                "本城建造奇观的速度+20%，且每建造一个奇观就为所有城市+5%建筑建造速度（不包括奇观）"),  
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_FINAL_NAME",                        "最终能力"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_BUILDER_FINAL_DESCRIPTION",                 "很厉害的最终能力，但还没有做"),  

    ("zh_Hans_CN",  "LOC_UNITCOMMAND_BUILDER_ADDFOOD_NAME",                             "食物补给"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_BUILDER_ADDFOOD_DESCRIPTION",                      "消耗建造者的1 [ICON_Charges] 劳动力，为本单元格+1 [icon_food] 食物（不可叠加，不可与生产力支援共存）"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_BUILDER_ADDFOOD_DISABLED_NOT_HOME",                "[COLOR_Red]单位需要位于己方境内[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_BUILDER_ADDFOOD_DISABLED_ENABLED",                 "[COLOR_Red]该单元格已经建立食物补给[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_UNITCOMMAND_BUILDER_ADDPROD_NAME",                             "生产力支援"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_BUILDER_ADDPROD_DESCRIPTION",                      "消耗建造者的1 [ICON_Charges] 劳动力，为本单元格+1 [ICON_Production] 生产力（不可叠加，不可与食物补给共存）"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_BUILDER_ADDPROD_DISABLED_NOT_HOME",                "[COLOR_Red]单位需要位于己方境内[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_BUILDER_ADDPROD_DISABLED_ENABLED",                 "[COLOR_Red]该单元格已经建立生产力支援[ENDCOLOR]"),


    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_EXPEDITION_NAME",                   "给养保障"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_EXPEDITION_DESCRIPTION",            "本城生产的开拓者不消耗 [ICON_CITIZEN] 人口，且+1 [ICON_MOVEMENT] 移动力。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_METROPOLIS_NAME",                   "母城"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_METROPOLIS_DESCRIPTION",            "每有一座新城市建立，就让本城+1 [ICON_Citizen] 人口，+2 [ICON_Housing] 住房，+1 [ICON_Amenities] 宜居度。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_SURPLUS_NAME",                      "盈余物流"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_SURPLUS_DESCRIPTION",               "本城每有一个非专业区域，通往本城的国内商路就+1 [ICON_Food] 食物；每有一个专业区域，通往本城的国内商路就+1 [ICON_Production] 生产力"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_FRONTIER_TOWN_NAME",                "拓荒驻地"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_FRONTIER_TOWN_DESCRIPTION",         "本城生产的开拓者，可以使用“扩建城市”行动，消耗自身并为城市额外增加一个专业区域上限，+1 [ICON_Citizen] 人口，+50%单元格获取速度。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_WAREHOUSE_NAME",                    "仓储管理"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_WAREHOUSE_DESCRIPTION",             "通往本城的 [ICON_TradeRoute] 国内商路占用 [ICON_TradeRoute] 商路容量减半（向上取整），每有一条通往本城的 [ICON_TRADEROUTE] 国内商路，就为本城每位公民+0.5 [ICON_food] 食物。"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_FINAL_NAME",                        "最终能力"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_MANAGER_FINAL_DESCRIPTION",                 "很厉害的最终能力，但还没有做"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_SETTLER_GETPLOT_NAME",                             "扩建城市"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_SETTLER_GETPLOT_DESCRIPTION",                      "消耗该开拓者，为本城增加1 [ICON_CITIZEN] 人口，并允许本城市可以无视人口限制额外建造一个专业区域，本城+50%单元格获取速度。（每座城市只能使用一次）"),
    ("zh_Hans_CN",  "LOC_UNITCOMMAND_SETTLER_GETPLOT_DESCRIPTION_DISABLED",             "[COLOR_Red]你必须位于你所拥有的城市的市中心[ENDCOLOR]"),

    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_LIBRARIANS_NAME",                  "图书馆员"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_LIBRARIANS_DESCRIPTION",           "本城每位公民+0.5 [icon_culture] 文化值+0.5 [icon_science] 科技值"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_RESEARCHERS_NAME",                 "研究员"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_RESEARCHERS_DESCRIPTION",          "本城+50% [icon_science] 科技值"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_CONNOISSEURS_NAME",                "鉴赏家"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_CONNOISSEURS_DESCRIPTION",         "本城+50% [icon_culture] 文化值"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_PROFESSOR_NAME",                   "教授"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_PROFESSOR_DESCRIPTION",            "本城+100%产出的 [ICON_GreatPerson] 伟人点数"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_PIONEER_NAME",                     "先驱"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_PIONEER_DESCRIPTION",              "本城每产出1 [icon_science] 科技值或 [icon_culture] 文化值，就对远古科技或市政+1%研究速度，该效果对每过两个时代的科技和市政都减半一次"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_FINAL_NAME",                       "最终能力"),
    ("zh_Hans_CN",  "LOC_GOVERNOR_PROMOTION_EDUCATOR_FINAL_DESCRIPTION",                "很厉害的最终能力，但还没有做");

   

