

update Eras set GreatPersonBaseCost = GreatPersonBaseCost * 1.5;

INSERT INTO Types (Type,	Kind) VALUES
--巴寡妇清  --种水银 水银城市造古典奇观加速
('GREAT_PERSON_INDIVIDUAL_WIDOW_QING',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--范蠡   商业中心+50%相邻 商业中心相邻转琴
('GREAT_PERSON_INDIVIDUAL_FAN_LI',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--阿尼尤斯·普洛卡姆斯   商路
('GREAT_PERSON_INDIVIDUAL_PLOCAMUS',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--子贡  使者
('GREAT_PERSON_INDIVIDUAL_ZI_GONG',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--塞尔吉乌斯 种珍珠 珍珠城市给商路
('GREAT_PERSON_INDIVIDUAL_SERGIUS',	'KIND_GREAT_PERSON_INDIVIDUAL'),

--拉美西斯二世  信仰买奇观
('GREAT_PERSON_INDIVIDUAL_RAMSES_II',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--郑国  水渠降价，水渠加区域粮相邻
('GREAT_PERSON_INDIVIDUAL_ZHENG_GUO',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--希波丹姆  加区域，区域加瓶
('GREAT_PERSON_INDIVIDUAL_HIPPODAMUS',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--维特鲁威  加区域，区域加琴
('GREAT_PERSON_INDIVIDUAL_VITRUVIUS',	'KIND_GREAT_PERSON_INDIVIDUAL'),

--亚历山大里亚的希罗
--('GREAT_PERSON_INDIVIDUAL_HERON',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--祖冲之
('GREAT_PERSON_INDIVIDUAL_ZUCHONGZHI',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--阿基米德
('GREAT_PERSON_INDIVIDUAL_ARCHIMEDES',	'KIND_GREAT_PERSON_INDIVIDUAL'),
--modofiertype
--欧几里得
('DA_MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER',	'KIND_MODIFIER');

INSERT INTO GreatPersonIndividuals (GreatPersonIndividualType,	Name,	GreatPersonClassType,	EraType,	Gender,	ActionCharges,	ActionRequiresCompletedDistrictType) VALUES
--巴寡妇清
('GREAT_PERSON_INDIVIDUAL_WIDOW_QING',	'LOC_GREAT_PERSON_INDIVIDUAL_WIDOW_QING_NAME',	'GREAT_PERSON_CLASS_MERCHANT',	'ERA_CLASSICAL',	'W',	1,	null),
--范蠡
('GREAT_PERSON_INDIVIDUAL_FAN_LI',	'LOC_GREAT_PERSON_INDIVIDUAL_FAN_LI_NAME',	'GREAT_PERSON_CLASS_MERCHANT',	'ERA_CLASSICAL',	'M',	1,	'DISTRICT_COMMERCIAL_HUB'),
--阿尼尤斯·普洛卡姆斯
('GREAT_PERSON_INDIVIDUAL_PLOCAMUS',	'LOC_GREAT_PERSON_INDIVIDUAL_PLOCAMUS_NAME',	'GREAT_PERSON_CLASS_MERCHANT',	'ERA_CLASSICAL',	'M',	1,	'DISTRICT_COMMERCIAL_HUB'),
--子贡
('GREAT_PERSON_INDIVIDUAL_ZI_GONG',	'LOC_GREAT_PERSON_INDIVIDUAL_ZI_GONG_NAME',	'GREAT_PERSON_CLASS_MERCHANT',	'ERA_CLASSICAL',	'M',	1,	null),
--塞尔吉乌斯
('GREAT_PERSON_INDIVIDUAL_SERGIUS',	'LOC_GREAT_PERSON_INDIVIDUAL_SERGIUS_NAME',	'GREAT_PERSON_CLASS_MERCHANT',	'ERA_CLASSICAL',	'M',	1,	null),


--拉美西斯二世
('GREAT_PERSON_INDIVIDUAL_RAMSES_II',	'LOC_GREAT_PERSON_INDIVIDUAL_RAMSES_II_NAME',	'GREAT_PERSON_CLASS_ENGINEER',	'ERA_CLASSICAL',	'M',	1,	null),
--郑国
('GREAT_PERSON_INDIVIDUAL_ZHENG_GUO',	'LOC_GREAT_PERSON_INDIVIDUAL_ZHENG_GUO_NAME',	'GREAT_PERSON_CLASS_ENGINEER',	'ERA_CLASSICAL',	'M',	2,	'DISTRICT_CITY_CENTER'),
--希波丹姆
('GREAT_PERSON_INDIVIDUAL_HIPPODAMUS',	'LOC_GREAT_PERSON_INDIVIDUAL_HIPPODAMUS_NAME',	'GREAT_PERSON_CLASS_ENGINEER',	'ERA_CLASSICAL',	'M',	1,	'DISTRICT_CITY_CENTER'),
--维特鲁威
('GREAT_PERSON_INDIVIDUAL_VITRUVIUS',	'LOC_GREAT_PERSON_INDIVIDUAL_VITRUVIUS_NAME',	'GREAT_PERSON_CLASS_ENGINEER',	'ERA_CLASSICAL',	'M',	1,	'DISTRICT_CITY_CENTER'),


--祖冲之
('GREAT_PERSON_INDIVIDUAL_ZUCHONGZHI',	'LOC_GREAT_PERSON_INDIVIDUAL_ZUCHONGZHI_NAME',	'GREAT_PERSON_CLASS_SCIENTIST',	'ERA_CLASSICAL',	'M',	1,	'DISTRICT_CAMPUS'),
--阿基米德
('GREAT_PERSON_INDIVIDUAL_ARCHIMEDES',	'LOC_GREAT_PERSON_INDIVIDUAL_ARCHIMEDES_NAME',	'GREAT_PERSON_CLASS_SCIENTIST',	'ERA_CLASSICAL',	'M',	1,	'DISTRICT_CAMPUS');
--亚历山大里亚的希罗
--('GREAT_PERSON_INDIVIDUAL_HERON',	'LOC_GREAT_PERSON_INDIVIDUAL_HERON_NAME',	'GREAT_PERSON_CLASS_SCIENTIST',	'ERA_CLASSICAL',	'M',	1,	'DISTRICT_CAMPUS');
update GreatPersonIndividuals set ActionRequiresIncompleteWonder = 1 where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_RAMSES_II';
--update GreatPersonIndividuals set ActionCharges = 2 where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_COLAEUS';
update GreatPersonIndividuals set ActionRequiresOwnedTile = 0, ActionRequiresCityStateTerritory = 1 where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_ZI_GONG';

--用lua来高亮地块的伟人
update GreatPersonIndividuals set ActionEffectTileHighlighting = 0 where GreatPersonIndividualType in 
	('GREAT_PERSON_INDIVIDUAL_WIDOW_QING', 'GREAT_PERSON_INDIVIDUAL_SERGIUS');
--欧几里得
update GreatPersonIndividuals set ActionCharges = 2 , ActionRequiresCompletedDistrictType = 'DISTRICT_CAMPUS' where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_EUCLID';
--张衡
update GreatPersonIndividuals set ActionEffectTextOverride = 'LOC_GREATPERSON_ZHANG_HENG_ACTIVE' where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_ZHANG_HENG';
--阿基米德
update GreatPersonIndividuals set ActionEffectTextOverride = 'LOC_GREAT_PERSON_INDIVIDUAL_ARCHIMEDES_ACTIVE' where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_ARCHIMEDES';

INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId,AttachmentTargetType) VALUES 
--巴寡妇清
('GREAT_PERSON_INDIVIDUAL_WIDOW_QING', 'GREATPERSON_WIDOW_QING_EMPTY','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
--范蠡
--('GREAT_PERSON_INDIVIDUAL_FAN_LI', 'GREATPERSON_FANLI_GOLD','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_FAN_LI', 'GREATPERSON_FANLI_GOLD_ADJACENCY_MODIFIER','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_FAN_LI', 'GREATPERSON_FANLI_GOLD_ADJACENCY_TO_CULTURE','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
--阿尼尤斯·普洛卡姆斯
('GREAT_PERSON_INDIVIDUAL_PLOCAMUS', 'PLOCAMUS_TRADE_ROUTE_CAPACITY','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
('GREAT_PERSON_INDIVIDUAL_PLOCAMUS', 'GREATPERSON_COMMERCIAL_ADD_ADJACENCY','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),

-- ('GREAT_PERSON_INDIVIDUAL_PLOCAMUS', 'GREATPERSON_GOLD_FROM_INCOMING_FOREIGN_ROUTES_PLOCAMUS','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'), 
-- ('GREAT_PERSON_INDIVIDUAL_PLOCAMUS', 'GREATPERSON_GOLD_TO_INCOMING_FOREIGN_ROUTES_PLOCAMUS','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'), 
--子贡
('GREAT_PERSON_INDIVIDUAL_ZI_GONG', 'GREATPERSON_ZI_GONG_EMPTY','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_UNIT_GREATPERSON'),
--塞尔吉乌斯
('GREAT_PERSON_INDIVIDUAL_SERGIUS', 'GREATPERSON_SERGIUS_EMPTY','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
--张骞
('GREAT_PERSON_INDIVIDUAL_ZHANG_QIAN', 'GREATPERSON_COMMERCIAL_ADD_ADJACENCY','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),


--拉美西斯二世
('GREAT_PERSON_INDIVIDUAL_RAMSES_II', 'GREAT_PERSON_RAMSES_II_DO_NOTHING','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_WONDER_IN_TILE'),
--郑国
--('GREAT_PERSON_INDIVIDUAL_ZHENG_GUO', 'GREATPERSON_ZHENG_GUO_GIFT_AQUEDUCT','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'), 
('GREAT_PERSON_INDIVIDUAL_ZHENG_GUO', 'GREATPERSON_ZHENG_GUO_AQUEDUCT_FOOD','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'), --失效，改用lua添加
--希波丹姆
('GREAT_PERSON_INDIVIDUAL_HIPPODAMUS', 'GREATPERSON_HIPPODAMUS_EXTRA_DISTRICT','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_CITY'),
('GREAT_PERSON_INDIVIDUAL_HIPPODAMUS', 'GREATPERSON_HIPPODAMUS_DISTRICT_YIELD','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_CITY'),
--维特鲁威
('GREAT_PERSON_INDIVIDUAL_VITRUVIUS', 'GREATPERSON_VITRUVIUS_EXTRA_DISTRICT','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_CITY'),
('GREAT_PERSON_INDIVIDUAL_VITRUVIUS', 'GREATPERSON_VITRUVIUS_DISTRICT_YIELD','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_CITY'),


--欧几里得
('GREAT_PERSON_INDIVIDUAL_EUCLID', 'DA_GREAT_PERSON_MODIFIER_EUCLID','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
--张衡
('GREAT_PERSON_INDIVIDUAL_ZHANG_HENG', 'DA_GREAT_PERSON_MODIFIER_EMPTY','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_CITY'),
--祖冲之
('GREAT_PERSON_INDIVIDUAL_ZUCHONGZHI', 'DA_GREAT_PERSON_MODIFIER_ZUCHONGZHI','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
--阿基米德
--('GREAT_PERSON_INDIVIDUAL_ARCHIMEDES', 'DA_GREAT_PERSON_MODIFIER_EMPTY','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER');
('GREAT_PERSON_INDIVIDUAL_ARCHIMEDES', 'ARCHIMEDES_ADJUST_PROPERTY','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
('GREAT_PERSON_INDIVIDUAL_ARCHIMEDES', 'GRANT_TECH_ERA_MEDIEVAL_BOOST','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER');


--亚历山大里亚的希罗
--('GREAT_PERSON_INDIVIDUAL_HERON', 'DA_GREAT_PERSON_MODIFIER_HERON','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_CITY');

delete from GreatPersonIndividualActionModifiers where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_COLAEUS' and ModifierId = 'GREATPERSON_FAITH_SMALL';
delete from GreatPersonIndividualActionModifiers where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_ZHANG_QIAN' and ModifierId like 'GREATPERSON_GOLD%';
--欧几里得
delete from GreatPersonIndividualActionModifiers where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_EUCLID' and ModifierId = 'GREATPERSON_1MEDIEVALTECHBOOST';
delete from GreatPersonIndividualActionModifiers where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_EUCLID' and ModifierId = 'GREATPERSON_MATHTECHBOOST';
--张衡
delete from GreatPersonIndividualActionModifiers where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_ZHANG_HENG' and ModifierId = 'GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_MATHEMATICS';
delete from GreatPersonIndividualActionModifiers where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_ZHANG_HENG' and ModifierId = 'GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_CEL_NAV';
delete from GreatPersonIndividualActionModifiers where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_ZHANG_HENG' and ModifierId = 'GREAT_PERSON_INDIVIDUAL_BOOST_OR_GRANT_ENGINEERING';

INSERT INTO Modifiers (ModifierId, 			ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
--巴寡妇清
('GREATPERSON_WIDOW_QING_EMPTY', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, 0, NULL, NULL),
('GREATPERSON_WIDOW_QING_WONDER_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_WONDER_ERA_PRODUCTION', 1, 1, 0, NULL, 'RS_CITY_HAS_IMPROVED_RESOURCE_MERCURY'),
--范蠡
('GREATPERSON_FANLI_GOLD', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, 0, NULL, NULL),
('GREATPERSON_FANLI_GOLD_ADJACENCY_MODIFIER', 'MODIFIER_SINGLE_CITY_DISTRICT_ADJUST_YIELD_MODIFIER', 1, 1, 0, NULL, NULL),
('GREATPERSON_FANLI_GOLD_ADJACENCY_TO_CULTURE', 'MODIFIER_PLAYER_DISTRICT_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 1, 1, 0, NULL, NULL),

--阿尼尤斯·普洛卡姆斯
('PLOCAMUS_TRADE_ROUTE_CAPACITY', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', 1, 1, 0, NULL, NULL), 
('GREATPERSON_COMMERCIAL_ADD_ADJACENCY', 'MODIFIER_CITY_DISTRICTS_ADJUST_BASE_YIELD_CHANGE', 1, 1, 0, NULL, 'RS_PLOT_HAS_DISTRICT_COMMERCIAL_HUB'), 

-- ('GREATPERSON_GOLD_FROM_INCOMING_FOREIGN_ROUTES_PLOCAMUS', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FROM_OTHERS', 1, 1, 0, NULL, NULL), 
-- ('GREATPERSON_GOLD_TO_INCOMING_FOREIGN_ROUTES_PLOCAMUS', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS', 1, 1, 0, NULL, NULL),
--子贡
('GREATPERSON_ZI_GONG_EMPTY', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, 0, NULL, NULL),
--塞尔吉乌斯
('GREATPERSON_SERGIUS_EMPTY', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, 0, NULL, 'RS_PLOT_HAS_IMPROVEMENT_FISHING_BOATS'),
('GREATPERSON_SERGIUS_TRADE_ROUTE_CAPACITY', 'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_CAPACITY', 1, 1, 0, NULL, 'RS_CITY_HAS_IMPROVED_RESOURCE_PEARLS'),


--拉美西斯二世
('GREAT_PERSON_RAMSES_II_DO_NOTHING', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, 0, NULL, NULL),
--郑国
--('GREATPERSON_ZHENG_GUO_GIFT_AQUEDUCT', 'MODIFIER_SINGLE_CITY_GRANT_PRODUCTION_IN_CITY', 1, 0, 1, NULL, NULL),
('GREATPERSON_ZHENG_GUO_AQUEDUCT_FOOD', 'MODIFIER_SINGLE_CITY_DISTRICT_ADJACENCY', 0, 1, 0, NULL, NULL),
--希波丹姆
('GREATPERSON_HIPPODAMUS_EXTRA_DISTRICT', 'MODIFIER_SINGLE_CITY_EXTRA_DISTRICT', 1, 1, 0, NULL, NULL),
('GREATPERSON_HIPPODAMUS_DISTRICT_YIELD', 'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE', 0, 1, 0, NULL, NULL),
--维特鲁威
('GREATPERSON_VITRUVIUS_EXTRA_DISTRICT', 'MODIFIER_SINGLE_CITY_EXTRA_DISTRICT', 1, 1, 0, NULL, NULL),
('GREATPERSON_VITRUVIUS_DISTRICT_YIELD', 'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_CHANGE', 0, 1, 0, NULL, NULL),
--欧几里得
('DA_GREAT_PERSON_MODIFIER_EUCLID', 'MODIFIER_SINGLE_CITY_DISTRICT_ADJUST_YIELD_MODIFIER', 0, 1, 0, NULL, NULL),
--张衡
('DA_GREAT_PERSON_MODIFIER_EMPTY', 'MODIFIER_PLAYER_GRANT_YIELD', 0, 1, 0, NULL,NULL),
('DA_GREAT_PERSON_MODIFIER_ZHANG_HENG', 'MODIFIER_CITY_DISTRICTS_ADJUST_BASE_YIELD_CHANGE', 0, 1, 0, NULL,'DISTRICT_IS_CAMPUS'),
--祖冲之
('DA_GREAT_PERSON_MODIFIER_ZUCHONGZHI', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, 0, NULL,NULL),
--阿基米德
--('DA_ARCHIMEDES_EURAKE_FROM_ADJACENCY', 'MODIFIER_PLAYER_ADJUST_TECHNOLOGY_BOOST', 1, 1, 0, NULL,NULL),
('ARCHIMEDES_ADJUST_PROPERTY', 'MODIFIER_PLAYER_ADJUST_PROPERTY', 1, 1, 0, NULL,NULL),

--亚历山大里亚的希罗
('DA_GREAT_PERSON_MODIFIER_HERON', 'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST', 1, 1, 0, NULL,NULL);

update Modifiers set SubjectStackLimit = 1 where ModifierId in 
	('GREATPERSON_ZHENG_GUO_AQUEDUCT_FOOD', 'GREATPERSON_WIDOW_QING_WONDER_PRODUCTION'	,'DA_GREAT_PERSON_MODIFIER_EUCLID');

-- insert or replace into Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) select
-- 	'DA_ARCHIMEDES_EURAKE_FROM_ADJACENCY_'||numbers, 'MODIFIER_CITY_DISTRICTS_ATTACH_MODIFIER', 'RS_IS_'||(numbers * 4)||'_ADJACENCY_DISTRICT_CAMPUS_FIX'
-- 	from counter where numbers > 0 and numbers < 8;

-- insert or replace into ModifierArguments(ModifierId, Name, Value) select
-- 	'DA_ARCHIMEDES_EURAKE_FROM_ADJACENCY_'||numbers, 'ModifierId', 'DA_ARCHIMEDES_EURAKE_FROM_ADJACENCY'
-- 	from counter where numbers > 0 and numbers < 8;




INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
--巴寡妇清
('GREATPERSON_WIDOW_QING_EMPTY', 'Amount', '0'), 
('GREATPERSON_WIDOW_QING_EMPTY', 'YieldType', 'YIELD_GOLD'), 
('GREATPERSON_WIDOW_QING_WONDER_PRODUCTION', 'Amount', '25'), 
('GREATPERSON_WIDOW_QING_WONDER_PRODUCTION', 'EndEra', 'ERA_CLASSICAL'), 
('GREATPERSON_WIDOW_QING_WONDER_PRODUCTION', 'StartEra', 'ERA_ANCIENT'), 
('GREATPERSON_WIDOW_QING_WONDER_PRODUCTION', 'IsWonder', 1), 

--范蠡
('GREATPERSON_FANLI_GOLD', 'Amount', '0'), 
('GREATPERSON_FANLI_GOLD', 'YieldType', 'YIELD_GOLD'), 

('GREATPERSON_FANLI_GOLD_ADJACENCY_TO_CULTURE', 'YieldTypeToGrant', 'YIELD_CULTURE'), 
('GREATPERSON_FANLI_GOLD_ADJACENCY_TO_CULTURE', 'YieldTypeToMirror', 'YIELD_GOLD'), 

('GREATPERSON_FANLI_GOLD_ADJACENCY_MODIFIER', 'Amount', '50'), 
('GREATPERSON_FANLI_GOLD_ADJACENCY_MODIFIER', 'YieldType', 'YIELD_GOLD'), 

--阿尼尤斯·普洛卡姆斯
('PLOCAMUS_TRADE_ROUTE_CAPACITY', 'Amount', '1'), 
('GREATPERSON_COMMERCIAL_ADD_ADJACENCY', 'Amount', '3'), 
('GREATPERSON_COMMERCIAL_ADD_ADJACENCY', 'YieldType', 'YIELD_GOLD'), 

-- ('GREATPERSON_GOLD_FROM_INCOMING_FOREIGN_ROUTES_PLOCAMUS', 'Amount', '4'), 
-- ('GREATPERSON_GOLD_FROM_INCOMING_FOREIGN_ROUTES_PLOCAMUS', 'YieldType', 'YIELD_GOLD'), 
-- ('GREATPERSON_GOLD_TO_INCOMING_FOREIGN_ROUTES_PLOCAMUS', 'Amount', '4'), 
-- ('GREATPERSON_GOLD_TO_INCOMING_FOREIGN_ROUTES_PLOCAMUS', 'YieldType', 'YIELD_GOLD'), 
--子贡
('GREATPERSON_ZI_GONG_EMPTY', 'Amount', '0'), 
('GREATPERSON_ZI_GONG_EMPTY', 'YieldType', 'YIELD_GOLD'),
--塞尔吉乌斯
('GREATPERSON_SERGIUS_EMPTY', 'Amount', '0'), 
('GREATPERSON_SERGIUS_EMPTY', 'YieldType', 'YIELD_GOLD'),
('GREATPERSON_SERGIUS_TRADE_ROUTE_CAPACITY', 'Amount', '1'),

--拉二
('GREAT_PERSON_RAMSES_II_DO_NOTHING', 'Amount', '0'), 
('GREAT_PERSON_RAMSES_II_DO_NOTHING', 'YieldType', 'YIELD_GOLD'), 

--郑国
--('GREATPERSON_ZHENG_GUO_GIFT_AQUEDUCT', 'Amount', '100'), 
--('GREATPERSON_ZHENG_GUO_GIFT_AQUEDUCT', 'KeepOverflow', '0'),
('GREATPERSON_ZHENG_GUO_AQUEDUCT_FOOD', 'Amount', '1'), 
('GREATPERSON_ZHENG_GUO_AQUEDUCT_FOOD', 'Description', 'LOC_ZHENGGUO_AQUEDUCT_FOOD'), 
('GREATPERSON_ZHENG_GUO_AQUEDUCT_FOOD', 'DistrictType', 'DISTRICT_AQUEDUCT'), 
('GREATPERSON_ZHENG_GUO_AQUEDUCT_FOOD', 'YieldType', 'YIELD_FOOD'),
--希波丹姆
('GREATPERSON_HIPPODAMUS_EXTRA_DISTRICT', 'Amount', '1'),
('GREATPERSON_HIPPODAMUS_DISTRICT_YIELD', 'Amount', '1'), 
('GREATPERSON_HIPPODAMUS_DISTRICT_YIELD', 'YieldType', 'YIELD_SCIENCE'), 
--维特鲁威
('GREATPERSON_VITRUVIUS_EXTRA_DISTRICT', 'Amount', '1'),
('GREATPERSON_VITRUVIUS_DISTRICT_YIELD', 'Amount', '1'), 
('GREATPERSON_VITRUVIUS_DISTRICT_YIELD', 'YieldType', 'YIELD_CULTURE'),


--欧几里得
('DA_GREAT_PERSON_MODIFIER_EUCLID',	'YieldType',	'YIELD_SCIENCE'),
('DA_GREAT_PERSON_MODIFIER_EUCLID',	'Amount',	'100'),
--张衡
('DA_GREAT_PERSON_MODIFIER_EMPTY', 'Amount', '0'), 
('DA_GREAT_PERSON_MODIFIER_EMPTY', 'YieldType', 'YIELD_GOLD'),
('DA_GREAT_PERSON_MODIFIER_ZHANG_HENG', 'Amount', '2'), 
('DA_GREAT_PERSON_MODIFIER_ZHANG_HENG', 'YieldType', 'YIELD_SCIENCE'),
--祖冲之
('DA_GREAT_PERSON_MODIFIER_ZUCHONGZHI', 'Amount', '314'), 
('DA_GREAT_PERSON_MODIFIER_ZUCHONGZHI', 'Scale', 1),
('DA_GREAT_PERSON_MODIFIER_ZUCHONGZHI', 'YieldType', 'YIELD_SCIENCE'),
--阿基米德
--('DA_ARCHIMEDES_EURAKE_FROM_ADJACENCY', 'Amount', '1'), 
('ARCHIMEDES_ADJUST_PROPERTY', 'Key', 'PROP_ARCHIMEDES'), 
('ARCHIMEDES_ADJUST_PROPERTY', 'Amount', 1), 
--亚历山大里亚的希罗
('DA_GREAT_PERSON_MODIFIER_HERON', 'TechType', 'TECH_STEAM_POWER'), 
('DA_GREAT_PERSON_MODIFIER_HERON', 'GrantTechIfBoosted', 0);

INSERT INTO ModifierStrings(ModifierId,	Context,	Text) VALUES
--巴寡妇清
('GREATPERSON_WIDOW_QING_EMPTY', 'Summary', 'LOC_WIDOW_QING_EMPTY'),
--范蠡
('GREATPERSON_FANLI_GOLD', 'Summary', 'LOC_FANLI_GOLD'),
('GREATPERSON_FANLI_GOLD_ADJACENCY_MODIFIER', 'Summary', 'LOC_FANLI_GOLD_ADJACENCY_MODIFIER'),
('GREATPERSON_FANLI_GOLD_ADJACENCY_TO_CULTURE', 'Summary', 'LOC_FANLI_GOLD_ADJACENCY_TO_CULTURE'),

--阿尼尤斯·普洛卡姆斯
('PLOCAMUS_TRADE_ROUTE_CAPACITY', 'Summary', 'LOC_PLOCAMUS_TRADE_ROUTE_CAPACITY'),
--子贡
('GREATPERSON_ZI_GONG_EMPTY', 'Summary', 'LOC_GREATPERSON_ZI_GONG_ADJACENCY_BONUS'),
--塞尔吉乌斯
('GREATPERSON_SERGIUS_EMPTY', 'Summary', 'LOC_SERGIUS_FISHING_EMPTY'),
--拉二
('GREAT_PERSON_RAMSES_II_DO_NOTHING', 'Summary', 'LOC_RAMSES_II_BUY_WONDER'), 
--郑国
--('GREATPERSON_ZHENG_GUO_AQUEDUCT', 'Summary', 'LOC_ZHENG_GUO_AQUEDUCT'),
('GREATPERSON_ZHENG_GUO_AQUEDUCT_FOOD', 'Summary', 	  'LOC_ZHENG_GUO_FOOD'),
--希波丹姆
('GREATPERSON_HIPPODAMUS_EXTRA_DISTRICT', 'Summary', 'LOC_HIPPODAMUS_EXTRA_DISTRICT'),
--维特鲁威
('GREATPERSON_VITRUVIUS_EXTRA_DISTRICT', 'Summary', 'LOC_VITRUVIUS_EXTRA_DISTRICT'),
--祖冲之
('DA_GREAT_PERSON_MODIFIER_ZUCHONGZHI', 'Summary', 'LOC_DA_GREAT_PERSON_MODIFIER_ZUCHONGZHI'),
--亚历山大里亚的希罗
('DA_GREAT_PERSON_MODIFIER_HERON', 'Summary', 'LOC_DA_GREAT_PERSON_MODIFIER_HERON');

insert or ignore into DynamicModifiers(ModifierType,	CollectionType,		EffectType) values
	('DA_MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER',			'COLLECTION_CITY_DISTRICTS',		'EFFECT_ADJUST_DISTRICT_YIELD_MODIFIER');

create table 'GreatPersonSpeedUp'(
	'GreatPersonIndividualType' TEXT NOT NULL,
	'SpeedUpWonder' BOOLEAN NOT NULL CHECK (SpeedUpWonder IN (0,1)) DEFAULT 0,
	'SpeedUpTechs' TEXT,
	PRIMARY KEY('GreatPersonIndividualType')
);

insert or replace into GreatPersonSpeedUp(GreatPersonIndividualType,	SpeedUpWonder,		SpeedUpTechs) values
	('GREAT_PERSON_RAMSES_II_DO_NOTHING',				1,		NULL),
	('GREAT_PERSON_INDIVIDUAL_IMHOTEP',					1,		NULL),
	('GREAT_PERSON_INDIVIDUAL_ISIDORE_OF_MILETUS',		1,		NULL),
	('GREAT_PERSON_INDIVIDUAL_FILIPPO_BRUNELLESCHI',	1,		NULL),	
	('GREAT_PERSON_INDIVIDUAL_SHAH_JAHAN',				1,		NULL),
	('GREAT_PERSON_INDIVIDUAL_GUSTAVE_EIFFEL',			1,		NULL);

